require 'sorting/insertion_sort'
require 'sum_of_three/sum_of_three'
require 'sum_of_three/sum_of_three_hash'
require 'sum_of_three/sum_of_three_sort'
require 'searching/linear_search_on_ordered_array'
